// Generated by CoffeeScript 1.3.1
var $$, $__classes, $__objects, getClassByName, getObjectById, registerClass, registerClasses, registerObject, registerObjects;

module('mvc');

include('core.js');

$__objects = {};

$__classes = {};

registerObject = function(id, object) {
  return $__objects[id] = object;
};

registerClass = function(name, klass) {
  return $__classes[name] = klass;
};

registerObjects = function(hash) {
  var id, obj, _results;
  _results = [];
  for (id in hash) {
    obj = hash[id];
    _results.push($__objects[id] = obj);
  }
  return _results;
};

registerClasses = function(hash) {
  var klass, name, _results;
  _results = [];
  for (name in hash) {
    klass = hash[name];
    _results.push($__classes[name] = klass);
  }
  return _results;
};

$$ = getObjectById = function(id) {
  return $__objects[id];
};

getClassByName = function(name) {
  return $__classes[name];
};

$(function() {
  return $.emit('load');
});

$.on('load', function() {
  return $.defer(function() {
    return $.emit('loaded');
  });
});

__embed('module.js');

__embed('controller.js');

__embed('view.js');

__embed('application.js');

$.extend(exports, {
  Module: Module,
  Controller: Controller,
  View: View,
  Application: Application,
  registerObject: registerObject,
  registerClass: registerClass,
  registerObjects: registerObjects,
  registerClasses: registerClasses,
  getObjectById: getObjectById,
  getClassByName: getClassByName,
  $$: $$,
  $__objects: $__objects,
  $__classes: $__classes
});
