// Generated by CoffeeScript 1.3.1
(function() {
  var argv, nlink, optimist;

  optimist = require('optimist');

  nlink = require('./nlink');

  argv = require('optimist').usage('JS linker.\nUsage: nlink [TARGETS]').options('o', {
    alias: 'outdir',
    describe: 'Output dir'
  }).options('f', {
    boolean: true,
    alias: 'force',
    "default": false,
    describe: 'Force replace existing files'
  }).options('c', {
    boolean: true,
    alias: 'compress',
    "default": false,
    describe: 'Compress JavaScript'
  }).options('I', {
    alias: 'indent',
    "default": 2,
    describe: 'Set file indent'
  }).options('i', {
    alias: 'include',
    describe: 'Add include dir'
  }).options('B', {
    alias: 'basedir',
    describe: 'Set base directory'
  }).options('b', {
    boolean: true,
    alias: 'bare',
    "default": false,
    describe: 'Skip wrap in namespace'
  }).options('v', {
    alias: 'version',
    describe: 'Show version'
  }).options('h', {
    alias: 'help',
    describe: 'Show help'
  }).argv;

  if (argv.h) {
    optimist.showHelp();
    process.exit(0);
  }

  if (argv.v) {
    console.log('nlink v' + nlink.VERSION);
    process.exit(0);
  }

  if (argv._.length === 0) {
    console.log('no targets'.red);
    optimist.showHelp();
    process.exit(0);
  }

  nlink(argv._, {
    outdir: argv.outdir,
    include: argv.include,
    force: argv.force,
    bare: argv.bare,
    basedir: argv.basedir,
    indent: argv.indent,
    compress: argv.compress
  });

}).call(this);
