// Generated by CoffeeScript 1.3.1
var fs, inspect, jsp;

jsp = require("uglify-js").parser;

fs = require('fs');

inspect = require('util').inspect;

console.log(inspect(jsp.parse(fs.readFileSync(__dirname + '/test2.js', 'utf-8')), false, null, true));
