// Generated by CoffeeScript 1.3.1
var ClassA, Module1, data, f,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

module('some-module');

require('jquery');

require('underscore');

require('callable1')(123);

require('call.able2')();

require('callable3')();

data = PRECOMPILE_TEMPLATE('test/tpl1.html');

Module1 = require("sm/" + "module");

f = function() {
  return console.log("ololo");
};

MIXIN('mixin.js');

MIXIN('mixin.js');

MIXIN('mixin.js');

ClassA = (function() {

  ClassA.name = 'ClassA';

  ClassA.prototype.A = PRECOMPILE(function() {
    return {
      test: 123,
      test2: "24234",
      test3: [1, 2, 3]
    };
  });

  function ClassA() {
    this.method2 = __bind(this.method2, this);

    this.method1 = __bind(this.method1, this);
    this.temp = require("sm/module");
  }

  ClassA.prototype.method1 = function() {
    return this.Tmpl = PRECOMPILE_TEMPLATE("test/tpl2.mu");
  };

  ClassA.prototype.method2 = function() {
    this.a = [1, 2, 3, 'a'];
    if (__indexOf.call(a, 'a') >= 0) {
      return this.method1();
    }
  };

  return ClassA;

})();

__extends(exports, {
  ClassA: ClassA
});
