// Generated by CoffeeScript 1.3.1

IFDEF(__DEBUG__, function() {
  DEFINE(TEST_FUN, function(a) {
    return console.log("olololololo");
  });
  DEFINE(TEST_OBJ, {
    test1: TEST_DEFINE,
    test2: 123,
    f: TEST_FUN
  });
  console.log('__DEBUG__', TEST_FUN, DEFINE);
  console.log('__DEBUG__', TEST_FUN, DEFINE);
  return console.log('__DEBUG__', TEST_FUN, DEFINE);
});
